# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.astp.postpartum-toc
# canonical: http://fhir.org/guides/astp/postpartum-toc/ImplementationGuide/fhir.astp.postpartum-toc
canonical: http://fhir.org/guides/astp/postpartum-toc
name: PostpartumTOC
title: USCDI+ Maternal Health Postpartum Transitions of Care (TOC) Implementation Guide
# description: Example Implementation Guide for getting started with SUSHI
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2025+
releaseLabel: ci-build
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: ASTP
  # url: http://example.org/example-publisher
  # email: test@example.org

# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
#
dependencies:
#  hl7.fhir.us.core: 6.1.0
#  hl7.terminology.r4: 6.5.0
#  hl7.fhir.uv.extensions.r4: 1.0.0
  hl7.fhir.us.core:
    version: 6.1.0
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: uscore
  hl7.fhir.uv.extensions.r4:  
    version: 5.2.0   
    id: ext       
  hl7.terminology.r4:
    version: 6.5.0
    uri: http://terminology.hl7.org/ImplementationGuide/hl7.terminology
    id: tho

##  hl7.fhir.us.mcode:
##    id: mcode
##    uri: http://hl7.org/fhir/us/mcode/ImplementationGuide/hl7.fhir.us.mcode
##    version: 1.0.0
##    hl7.fhir.uv.sdc: 3.0.0
# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
# The page file name is used as the key. If title is not provided,
# then the title will be generated from the file name.  If a
# generation value is not provided, it will be inferred from the
# file name extension.  Any subproperties that are valid filenames
# with supported extensions (e.g., .md/.xml) will be treated as
# sub-pages.
#
pages:
  index.md:
    title: Home
  background.md:
    title: Background
  spec.md:
    title: Specification
  ##artifacts.html:
    ##title: Artifacts Summary
  ##  conformance.md:
  ##    title: conformance
  guidance.md:
    title: Guidance
  examples.md: 
    title: Examples
  profiles-extensions.md:
    title: Profiles and Extensions
  search-parameters-and-operations.md:
    title: Search Parameters and Operations
  capability-statements.md:
    title: Capability Statements
  terminology.md:
    title: Terminology
  downloads.md:
    title: Downloads
  change-log.md:
    title: Change Log

# The parameters property represents IG.definition.parameter. Rather
# than a list of code/value pairs (as in the ImplementationGuide
# resource), the code is the YAML key. If a parameter allows repeating
# values, the value in the YAML should be a sequence/array.
# For parameters defined by core FHIR see:
# http://build.fhir.org/codesystem-guide-parameter-code.html
# For parameters defined by the FHIR Tools IG see:
# http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
parameters:
  excludettl: true
  show-inherited-invariants: false
  pin-canonicals: pin-multiples
  apply-jurisdiction: false
  apply-publisher: false
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - fsh-generated/includes

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │ The menu property will be used to generate the input/menu.xml file. The menu is represented    │
# │ as a simple structure where the YAML key is the menu item name and the value is the URL.       │
# │ The IG publisher currently only supports one level deep on sub-menus. To provide a             │
# │ custom menu.xml file, do not include this property and include a `menu.xml` file in            │
# │ input/includes. To use a provided input/includes/menu.xml file, delete the "menu"              │
# │ property below.                                                                                │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Background: background.html
  Specification: spec.html
  Guidance: guidance.html
  FHIR Artifacts:
    #Artifacts Summary: artifacts.html
    Profiles and Extensions: profiles-extensions.html
    Terminology: terminology.html
    Capability Statements: capability-statements.html
    Search Parameters and Operations: search-parameters-and-operations.html
  Examples: examples.html
  Downloads: downloads.html
  Change Log: change-log.html
# ╭───────────────────────────Less Common Implementation Guide Properties──────────────────────────╮
# │  Uncomment the properties below to configure additional properties on the ImplementationGuide  │
# │  resource. These properties are less commonly needed than those above.                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#
# Those who need more control or want to add additional details to the contact values can use
# contact directly and follow the format outlined in the ImplementationGuide resource and
# ContactDetail.
#
# contact:
#   - name: Bob Smith
#     telecom:
#       - system: email # phone | fax | email | pager | url | sms | other
#         value: bobsmith@example.org
#         use: work
#
#
# The global property corresponds to the IG.global property, but it
# uses the type as the YAML key and the profile as its value. Since
# FHIR does not explicitly disallow more than one profile per type,
# neither do we; the value can be a single profile URL or an array
# of profile URLs. If a value is an id or name, SUSHI will replace
# it with the correct canonical when generating the IG JSON.
#
# global:
#   Patient: http://example.org/fhir/StructureDefinition/my-patient-profile
#   Encounter: http://example.org/fhir/StructureDefinition/my-encounter-profile
#
#
# The resources property corresponds to IG.definition.resource.
# SUSHI can auto-generate all of the resource entries based on
# the FSH definitions and/or information in any user-provided
# JSON or XML resource files. If the generated entries are not
# sufficient or complete, however, the author can add entries
# here. If the reference matches a generated entry, it will
# replace the generated entry. If it doesn't match any generated
# entries, it will be added to the generated entries. The format
# follows IG.definition.resource with the following differences:
#   * use IG.definition.resource.reference.reference as the YAML key.
#   * if the key is an id or name, SUSHI will replace it with the
#     correct URL when generating the IG JSON.
#   * specify "omit" to omit a FSH-generated resource from the
#     resource list.
#   * if the exampleCanonical is an id or name, SUSHI will replace
#     it with the correct canonical when generating the IG JSON.
#   * groupingId can be used, but top-level groups syntax may be a
#     better option (see below).
# The following are simple examples to demonstrate what this might
# look like:
#

resources:
  Binary/example-binary:
    name: PDF Content of binary
    description: An example of binary resource with contents of a labor and delivery summary note.
    exampleBoolean: true
  DiagnosticReport/diagnosticreport-imaging-example:
    name: DiagnosticReport Imaging
    description: An example of an imaging report conforming to the  MH TOC Diagnostic Imaging Report Profile.
    exampleBoolean: true
  DocumentReference/discharge-summary-example:
    name: Hospitalist Discharge Summary
    description: An example of a hospitalists discharge summary note conforming to the MH TOC Discharge Summary Profile.
    exampleBoolean: true
  Observation/edd-example:
    name: Estimated Date of Delivery
    description: An example of an estimated date of delivery (EDD) observation instance to the MH TOC Estimated Date of Delivery Profile.
    exampleBoolean: true
  Condition/example-smm-condition-acute-myocardial-infarction:
    name: SMM Condition Acute Myocardial Infarction 
    description: An example of an instance of the SMM Condition Acute Myocardial Infarction Indicator conforming to the MH TOC Severe Maternal Morbidity Condition Acute Myocardial Infarction Profile.
    exampleBoolean: true
  Condition/example-smm-condition-aneurysm:
    name: SMM Condition Aneurysm
    description: An example of an instance of the SMM Condition Aneurysm Indicator conforming to the MH TOC Severe Maternal Morbidity Condition Aneurysm Profile.
    exampleBoolean: true
  Procedure/example-smm-procedure-hysterectomy:
    name: SMM Procedure Hysterectomy
    description: An example of an instance of the SMM Procedure Hysterectomy Indicator conforming to the MH TOC Severe Maternal Morbidity Hysterectomy Profile.
    exampleBoolean: true
  Procedure/example-smm-procedure-ventilation:
    name: SMM Procedure Ventilation
    description: An example of an instance of the SMM Procedure Ventilation Indicator conforming to the MH TOC Severe Maternal Morbidity Ventilation Profile.
    exampleBoolean: true
  FamilyMemberHistory/family-health-history-example:
    name: Family Member Health History
    description: An example of a family member health history with conditions conforming to the MH TOC Family Health History Profile.
    exampleBoolean: true
  Observation/gestational-age-example:
    name: Gestational Age
    description: An example of a recorded gestational age in weeks conforming to the MH TOC Gestational Age Profile.
    exampleBoolean: true
  ImagingStudy/imagingstudy-ob-fetal-dating:
    name: OB Fetal Dating ImagingStudy
    description: An example of an OB fetal dating Ultrasound conforming to the HL7 R4 ImagingStudy resource.
    exampleBoolean: true
  Observation/labor-type-example: 
    name: Labor Type
    description: An example of a recorded labor type conforming to the MH TOC Labor Type Profile.
    exampleBoolean: true
  DocumentReference/mh-toc-behavioral-health-history-example:
    name: Behavioral Health History Note
    description: An example of a behavioral health history note with a text attachement conforming to the MH TOC Behavioral Health History Profile.
    exampleBoolean: true
  DocumentReference/mh-toc-consult-note-example:
    name: Consultation Note
    description: An example of a consultation note conforming to the MH TOC Consult Note Profile.
    exampleBoolean: true
  Observation/mh-toc-delivery-date-example: 
    name: Delivery Date
    description: An example of a mother's delivery date conforming to the MH TOC Delivery Date Profile.
    exampleBoolean: true
  Observation/mh-toc-gravidity-example:
    name: Maternal Gravidity
    description: An example of a recorded maternal gravidity conforming to the MH TOC Gravidity Profile.
    exampleBoolean: true
  DocumentReference/mh-toc-labor-and-delivery-summary-example:
    name: Labor and Delivery Summary
    description: An example of a labor and delivery summary note conforming to the MH TOC Labor and Delivery Summary Profile.
    exampleBoolean: true
  Observation/mh-toc-parity-example:
    name: Maternal Parity
    description: An example of a recorded maternal parity conforming to the MH TOC Parity Profile.
    exampleBoolean: true
  DocumentReference/mh-toc-postpartum-summary-example:
    name: Postpartum Summary Note
    description: An example of a post partrum summary note conforming to the MH TOC Postpartum Summary Profile.
    exampleBoolean: true
  Observation/breastfeeding-status-example:
    name: Breastfeeding Status
    description: An example of a recorded breastfeeding status conforming to the MH TOC Breastfeeding Status Profile of a mother who is currently breastfeeding.
    exampleBoolean: true
  Observation/example-breastfeeding-intent:
    name: Breastfeeding Intent
    description: An example of a recorded breastfeeding intent conforming to the MH TOC Breastfeeding Intent Profile of a mother who intends to bottle feed.
    exampleBoolean: true







# resources:
#   Patient/my-example-patient:
#     name: My Example Patient
#     description: An example Patient
#     exampleBoolean: true
#   Patient/bad-example: omit
#
#
# Groups can control certain aspects of the IG generation.  The IG
# documentation recommends that authors use the default groups that
# are provided by the templating framework, but if authors want to
# use their own instead, they can use the mechanism below.  This will
# create IG.definition.grouping entries and associate the individual
# resource entries with the corresponding groupIds. If a resource
# is specified by id or name, SUSHI will replace it with the correct
# URL when generating the IG JSON.
#
# groups:
#   GroupA:
#     name: Group A
#     description: The Alpha Group
#     resources:
#     - StructureDefinition/animal-patient
#     - StructureDefinition/arm-procedure
#   GroupB:
#     name: Group B
#     description: The Beta Group
#     resources:
#     - StructureDefinition/bark-control
#     - StructureDefinition/bee-sting
#
#
# The ImplementationGuide resource defines several other properties
# not represented above. These properties can be used as-is and
# should follow the format defined in ImplementationGuide:
# * date
# * meta
# * implicitRules
# * language
# * text
# * contained
# * extension
# * modifierExtension
# * experimental
# * useContext
# * copyright
# * packageId
#
#
# ╭──────────────────────────────────────────SUSHI flags───────────────────────────────────────────╮
# │  The flags below configure aspects of how SUSHI processes FSH.                                 │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# The FSHOnly flag indicates if only FSH resources should be exported.
# If set to true, no IG related content will be generated.
# The default value for this property is false.
#
# FSHOnly: false
#
#
# When set to true, the "short" and "definition" field on the root element of an Extension will
# be set to the "Title" and "Description" of that Extension. Default is true.
#
# applyExtensionMetadataToRoot: true
#
#
# The instanceOptions property is used to configure certain aspects of how SUSHI processes instances.
# See the individual option definitions below for more detail.
#
instanceOptions:
  # When set to true, slices must be referred to by name and not only by a numeric index in order to be used
  # in an Instance's assignment rule. All slices appear in the order in which they are specified in FSH rules.
  # While SUSHI defaults to false for legacy reasons, manualSliceOrding is recommended for new projects.
  manualSliceOrdering: true # true | false
  # Determines for which types of Instances SUSHI will automatically set meta.profile
  # if InstanceOf references a profile:
  #
  # setMetaProfile: always # always | never | inline-only | standalone-only
  #
  #
  # Determines for which types of Instances SUSHI will automatically set id
  # if InstanceOf references a profile:
  #
  # setId: always # always | standalone-only
